'use strict';
const cfg=window.ZOPPLER_CONFIG||{};const api=String(cfg.API_BASE_URL||'').replace(/\/$/,'');let csrf='';const $=id=>document.getElementById(id);const now=new Date(),today=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);$('visitDate').min=today;$('visitDate').value=today;$('checkoutDate').min=today;$('checkoutDate').value=today;function syncCheckoutDate(){$('checkoutDate').min=$('visitDate').value||today;if($('checkoutDate').value<$('checkoutDate').min)$('checkoutDate').value=$('checkoutDate').min}$('visitDate').onchange=syncCheckoutDate;$('checkoutDate').onchange=syncCheckoutDate;$('modeLabel').textContent='PostgreSQL-connected server';
function safe(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function request(path,opts={}){const headers={'X-CSRF-Token':csrf,...(opts.headers||{})};if(!(opts.body instanceof FormData))headers['Content-Type']='application/json';let r;try{r=await fetch(api+path,{credentials:'same-origin',...opts,headers})}catch(_){throw new Error('Cannot reach the server. Check your connection and try again.')}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed ('+r.status+')');return data}
async function all(){return request('/api/visits')}
async function create(data){return request('/api/visits',{method:'POST',body:data})}
async function update(id,status){return request('/api/visits/'+encodeURIComponent(id)+'/status',{method:'PATCH',body:JSON.stringify({status})})}
async function initialize(){try{const s=await request('/api/session');csrf=s.csrf;if(s.authenticated){$('loginPanel').classList.add('hidden');$('dashboard').classList.remove('hidden');if(!$('admin').classList.contains('hidden'))render()} }catch(e){$('modeLabel').textContent='Server unavailable: '+e.message}}
const initialization=initialize();
function show(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==name));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='admin'&&!$('dashboard').classList.contains('hidden'))render();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
$('visitForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter||e.currentTarget.querySelector('button[type="submit"]');b.disabled=true;$('submitMsg').className='notice';$('submitMsg').textContent='Submitting your request…';const data=new FormData(e.target);let requestToken=sessionStorage.getItem('zopplerVisitToken');if(!requestToken){requestToken=crypto.randomUUID().replace(/-/g,'');sessionStorage.setItem('zopplerVisitToken',requestToken)}data.append('requestToken',requestToken);try{const v=await create(data);$('submitMsg').textContent='Request submitted. Your reference number: '+v.id+'. Save this number to check your status.';sessionStorage.removeItem('zopplerVisitToken');e.target.reset();$('visitDate').value=today;$('checkoutDate').value=today}catch(err){$('submitMsg').className='error';$('submitMsg').textContent='Unable to submit: '+err.message+' Please wait a moment and submit again; your request will not be duplicated.'}finally{b.disabled=false}};
$('statusForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter||e.currentTarget.querySelector('button');const id=$('reference').value.trim().toUpperCase();$('reference').value=id;button.disabled=true;$('statusResult').className='result muted';$('statusResult').textContent='Checking request…';try{const v=await request('/api/visits/'+encodeURIComponent(id)+'/status');$('statusResult').className='result notice';$('statusResult').innerHTML='<h2>'+safe(v.id)+'</h2><p>Status: <strong>'+safe(v.status)+'</strong></p><p>Visit date: '+safe(v.date)+' · '+safe(v.time)+'</p>'}catch(err){$('statusResult').className='result error';$('statusResult').textContent=err.message}finally{button.disabled=false}};
$('loginForm').onsubmit=async e=>{e.preventDefault();await initialization;const button=e.submitter;button.disabled=true;$('loginError').className='error';try{const v=await request('/api/login',{method:'POST',body:JSON.stringify({username:$('adminUsername').value.trim(),password:$('demoCode').value})});csrf=v.csrf;$('loginError').textContent='';$('loginPanel').classList.add('hidden');$('dashboard').classList.remove('hidden');$('demoCode').value='';render()}catch(err){$('loginError').textContent=err.message}finally{button.disabled=false}};
let resetToken='';
function openResetRequest(){resetToken='';$('resetRequestForm').reset();$('resetConfirmForm').reset();$('resetRequestForm').classList.remove('hidden');$('resetConfirmForm').classList.add('hidden');$('otpFields').classList.remove('hidden');$('resetOtpEmail').required=false;$('resetOtp').required=false;$('resetMessage').textContent='';$('loginPanel').classList.add('hidden');$('resetPanel').classList.remove('hidden')}
function backToLogin(){history.replaceState({},'',location.pathname);resetToken='';$('resetPanel').classList.add('hidden');$('loginPanel').classList.remove('hidden');$('resetRequestForm').classList.remove('hidden');$('resetConfirmForm').classList.add('hidden');$('resetMessage').textContent=''}
$('showReset').onclick=openResetRequest;
document.querySelectorAll('.back-login').forEach(b=>b.onclick=backToLogin);
$('resetRequestForm').onsubmit=async e=>{e.preventDefault();await initialization;const button=e.submitter;button.disabled=true;$('resetMessage').className='notice';$('resetMessage').textContent='Sending reset instructions…';try{const email=$('resetEmail').value.trim().toLowerCase();const v=await request('/api/password-reset/request',{method:'POST',body:JSON.stringify({email})});$('resetMessage').textContent=v.message+' Enter the OTP below, or open the link in the email.';$('resetOtpEmail').value=email;$('resetOtpEmail').required=true;$('resetOtp').required=true;$('resetRequestForm').classList.add('hidden');$('resetConfirmForm').classList.remove('hidden')}catch(err){$('resetMessage').className='error';$('resetMessage').textContent=err.message}finally{button.disabled=false}};
const pageParams=new URLSearchParams(location.search);resetToken=pageParams.get('reset')||'';
if(pageParams.get('view')==='admin')show('admin');
if(resetToken){show('admin');$('loginPanel').classList.add('hidden');$('resetPanel').classList.remove('hidden');$('resetRequestForm').classList.add('hidden');$('resetConfirmForm').classList.remove('hidden');$('otpFields').classList.add('hidden')}
$('resetConfirmForm').onsubmit=async e=>{e.preventDefault();await initialization;const button=e.submitter;$('resetMessage').className='error';if($('newPassword').value!==$('confirmPassword').value){$('resetMessage').textContent='Passwords do not match';return}button.disabled=true;try{await request('/api/password-reset/confirm',{method:'POST',body:JSON.stringify({token:resetToken,email:$('resetOtpEmail').value.trim().toLowerCase(),otp:$('resetOtp').value.trim(),username:$('newUsername').value.trim(),password:$('newPassword').value})});history.replaceState({},'',location.pathname);resetToken='';$('resetConfirmForm').reset();$('resetPanel').classList.add('hidden');$('loginPanel').classList.remove('hidden');$('loginError').className='notice';$('loginError').textContent='Login ID and password updated successfully. Sign in with your new credentials.'}catch(err){$('resetMessage').textContent=err.message}finally{button.disabled=false}};
$('showChangePassword').onclick=()=>{$('changePasswordPanel').classList.remove('hidden');$('currentPassword').focus()};
$('cancelChangePassword').onclick=()=>{$('changePasswordPanel').classList.add('hidden');$('changePasswordForm').reset();$('changePasswordMessage').textContent=''};
$('changePasswordForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;const current=$('currentPassword').value,newPassword=$('changeNewPassword').value;$('changePasswordMessage').className='error';if(newPassword!==$('changeConfirmPassword').value){$('changePasswordMessage').textContent='New passwords do not match';return}button.disabled=true;try{await request('/api/change-password',{method:'POST',body:JSON.stringify({currentPassword:current,newPassword})});$('changePasswordForm').reset();$('changePasswordPanel').classList.add('hidden');$('dashboard').classList.add('hidden');$('loginPanel').classList.remove('hidden');const s=await request('/api/session');csrf=s.csrf;$('loginError').className='notice';$('loginError').textContent='Password changed successfully. Sign in with your new password.'}catch(err){$('changePasswordMessage').textContent=err.message}finally{button.disabled=false}};
$('logout').onclick=async()=>{try{await request('/api/logout',{method:'POST'});$('dashboard').classList.add('hidden');$('loginPanel').classList.remove('hidden');$('demoCode').value='';const s=await request('/api/session');csrf=s.csrf}catch(err){alert(err.message)}};
async function render(){try{const a=await all();$('total').textContent=a.length;$('pending').textContent=a.filter(x=>x.status==='Pending').length;$('approved').textContent=a.filter(x=>x.status==='Approved').length;$('onsite').textContent=a.filter(x=>x.status==='Checked In').length;const q=$('search').value.toLowerCase(),f=$('filter').value;const shown=a.filter(v=>(!f||v.status===f)&&[v.name,v.company,v.id,v.host].some(x=>String(x||'').toLowerCase().includes(q)));$('requests').innerHTML=shown.map(v=>`<article class="request">${v.photoUrl?`<img class="visitor-photo" src="${safe(v.photoUrl)}" alt="Photo of ${safe(v.name)}">`:''}<div class="request-body"><div class="request-top"><h3>${safe(v.name)}</h3><span class="badge ${safe(v.status).replace(/ /g,'-')}">${safe(v.status)}</span></div><p><strong>${safe(v.id)}</strong> · Arrival: ${safe(v.date)} at ${safe(v.time)}</p><p>Expected checkout: ${safe(v.expectedCheckoutDate||'Not captured')} ${v.expectedCheckoutTime?'at '+safe(v.expectedCheckoutTime):''}</p><p>${safe(v.company)} · ${safe(v.mobile)} · ${safe(v.email)}</p><p>Aadhaar: ${safe(v.aadhar)}</p><p>Meeting: ${safe(v.host)} (${safe(v.department)})</p><p>Purpose: ${safe(v.purpose)}</p><div class="actions">${v.status==='Pending'?`<button class="primary" data-id="${safe(v.id)}" data-status="Approved">Approve</button><button class="reject" data-id="${safe(v.id)}" data-status="Rejected">Reject</button>`:''}${v.status==='Approved'?`<button class="primary" data-id="${safe(v.id)}" data-status="Checked In">Check in</button>`:''}${v.status==='Checked In'?`<button class="secondary" data-id="${safe(v.id)}" data-status="Checked Out">Check out</button>`:''}</div></div></article>`).join('')||'<p class="muted">No matching visitor requests.</p>'}catch(err){$('requests').textContent='Unable to load requests: '+err.message}}
new MutationObserver(()=>{const count=$('requests').querySelectorAll('.request').length;$('resultCount').textContent=count+' request'+(count===1?'':'s');$('lastUpdated').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}).observe($('requests'),{childList:true});
$('refreshDashboard').onclick=async e=>{const button=e.currentTarget;button.disabled=true;button.textContent='Refreshing…';try{await render()}finally{button.disabled=false;button.textContent='Refresh'}};
$('requests').onclick=async e=>{const b=e.target.closest('button[data-status]');if(!b)return;if(!confirm('Change visitor status to '+b.dataset.status+'?'))return;try{await update(b.dataset.id,b.dataset.status);render()}catch(err){alert(err.message)}};$('search').oninput=render;$('filter').onchange=render;
$('export').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const a=await all();const keys=['id','name','mobile','email','company','host','department','date','time','expectedCheckoutDate','expectedCheckoutTime','purpose','status','createdAt','updatedAt'];const csv=[keys.join(','),...a.map(v=>keys.map(k=>'"'+String(v[k]??'').replace(/^[=+@-]/,'\'$&').replace(/"/g,'""')+'"').join(','))].join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='zoppler-visitors.csv';link.click();URL.revokeObjectURL(url)}catch(err){alert('Unable to export: '+err.message)}finally{button.disabled=false}};
async function optimiseVisitorPhoto(data){const photo=data.get('photo');if(!(photo instanceof File)||photo.size<=900000||!window.createImageBitmap)return;const bitmap=await createImageBitmap(photo);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(blob&&blob.size<photo.size){const filename=(photo.name||'visitor-photo').replace(/\.[^.]+$/,'')+'.jpg';data.set('photo',new File([blob],filename,{type:'image/jpeg'}))}}
$('visitForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter||e.currentTarget.querySelector('button[type="submit"]');b.disabled=true;$('submitMsg').className='notice';const data=new FormData(e.target);try{$('submitMsg').textContent='Preparing your photo for a faster upload...';await optimiseVisitorPhoto(data);$('submitMsg').textContent='Submitting your request...';let requestToken=sessionStorage.getItem('zopplerVisitToken');if(!requestToken){requestToken=crypto.randomUUID().replace(/-/g,'');sessionStorage.setItem('zopplerVisitToken',requestToken)}data.append('requestToken',requestToken);const v=await create(data);$('submitMsg').textContent='Request submitted. Your reference number: '+v.id+'. Save this number to check your status.';sessionStorage.removeItem('zopplerVisitToken');e.target.reset();$('visitDate').value=today;$('checkoutDate').value=today}catch(err){$('submitMsg').className='error';$('submitMsg').textContent='Unable to submit: '+err.message+' Please wait a moment and submit again; your request will not be duplicated.'}finally{b.disabled=false}};
